### ISSUE TITLE
Can't import `genomicranges` with Python 3.11

### ISSUE THREAD

**Issue by nleroy917** [BiocPy/GenomicRanges#11]
### Overview
Hello - excited about this library!

I was attempting to do some testing/experimenting and I currently run Python `3.11.4`, but I was running into an import error with `numpy`. 

### Steps to reproduce
1. Install fresh virtual environment with python 3.11: 
```
pyenv local 3.11.4
python -m venv venv
source venv/bin/activate
```
2. Install `GenomicRanges`
```
pip install genomicranges
```
3. Attempt import:
```python
import genomicranges
```
4. Observe error
```
File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
```

### To resolve
I can resolve this by just downgrading python to 3.10.

### Additional information
It [seems like](https://github.com/pandas-dev/pandas/issues/50945#issuecomment-1401301121) `numpy` only supports python 3.11 in `1.23.3` and up. I see this package [has it pinned to 1.22.1](https://github.com/BiocPy/GenomicRanges/blob/bcfabbde22b9b8f9d6574381f14470a3a58c09eb/setup.cfg#L55). Is it possible to bump `numpy` to `>1.23.3`? Or just unpin it?

Let me know if you need any more information!

Nathan

**Comment by jkanche** [comment]
Thanks for reporting this, I've gotten down to the real issue that forced me to pin the versions.
