### ISSUE TITLE
`IRanges.to_pandas` fails if there are mcols

### ISSUE THREAD

**Issue by balwierz** [BiocPy/GenomicRanges#125]
The following code fails
```py
import genomicranges as gr
gr.GenomicRanges(seqnames=["A"], ranges=IRanges(start=[0], width=[10])).reduce().to_pandas()
```

Without `reduce()` it works.

**Comment by balwierz** [comment]
I found the problem and a solution
`IRanges.to_pandas` is buggy, concatenation with mcols should read:
`output = pd.concat([output, self._mcols.to_pandas()], ignore_index=True, axis=1)`
Without `axis=1` it concatenates vertically. From my understanding there should be `ignore_index=True` too

**Comment by jkanche** [comment]
Thank you, Just fixed this in both the packages. let me know if you continue to see this issue after updating.
