### ISSUE TITLE
8 bits is too little to store all contigs of hg38

### ISSUE THREAD

**Issue by balwierz** [BiocPy/GenomicRanges#127]
The current human genome has 455 contigs in the assembly.
`https://hgdownload.soe.ucsc.edu/goldenpath/hg38/bigZips/hg38.chrom.sizes`

`int8` is too small to hold them

**Comment by jkanche** [comment]
Thank you for reporting this. This should've already been resolved. Can you let me know what version of genomicranges you are using? Also helps if you can provide an MRE for me to debug.

**Comment by jkanche** [comment]
```py
import pandas as pd
hg38 = pd.read_csv("http://hgdownload.soe.ucsc.edu/goldenpath/hg38/bigZips/hg38.chrom.sizes", sep="\t", header=None, names=["chrm", "sizes"])
hg38.head(3)

import genomicranges as gr
seqinfo = gr.SeqInfo(seqnames=hg38["chrm"], seqlengths=hg38["sizes"])
print(seqinfo)
```

![image](https://github.com/user-attachments/assets/55f25120-3a0c-431a-a3d2-3bceb30e24e8)

**Comment by balwierz** [comment]
Hi.
Thanks for fixing stuff quickly!
I really appreciate it.

So the problem was with merging two `GenomicRanges` objects, One of which had 8bit seqnames, and the other was 16bit seqnames. The result was 8bit! So there was truncation.
But since now merging `GenomicRanges` should be fine, maybe this will not be a problem anymore.

**Comment by jkanche** [comment]
awesome, please let us know if you run into this again and feel free to reopen this issue. Thank you!
