### ISSUE TITLE
No way to set up an empty GenomicRanges like in BiocFrame

### ISSUE THREAD

**Issue by DiDeoxy** [BiocPy/GenomicRanges#4]
If just `numberofRows` is supplied to `GenomicRanges` an exception is raised despite type hinting indicating this is acceptable. If empty `data` is also supplied another exception is raised, if `data` with empty list values for required columns is supplied an exception is raised. Only way to get an "empty" GenomicRanges is with lists filled with `None`s of the desired length of `numberOfRows`.

**Comment by jkanche** [comment]
https://github.com/BiocPy/GenomicRanges/commit/e368fb9a70613bd8bd11331ecf22c24b90e10a7d
