### ISSUE TITLE
Documentation for version 0.4.1 is outdated

### ISSUE THREAD

**Issue by nsheff** [BiocPy/GenomicRanges#46]
Documentation for 0.4.1 is no longer working.

This is no longer correct: https://biocpy.github.io/GenomicRanges/tutorial.html#overlap-based-methods

```
import genomicranges
import pandas as pd

df = pd.DataFrame(
    {
        "seqnames": ["chr1", "chr2", "chr1", "chr3", "chr2"],
        "starts": [101, 102, 103, 104, 109],
        "ends": [112, 103, 128, 134, 111],
        "strand": ["*", "-", "*", "+", "-"],
        "score": range(0, 5),
        "GC": [random() for _ in range(5)],
    }
)

gr = GenomicRanges.from_pandas(df)
```

Gives: `NameError: name 'GenomicRanges' is not defined

Also:

```
subject = genomicranges.from_pandas(df_subject)

df_query = pd.DataFrame(
    {"seqnames": ["chr2",], "starts": [4], "ends": [6], "strand": ["+"]}
)

query = genomicranges.from_pandas(df_query)

# findOverlaps
res = subject.find_overlaps(query, queryType="within")
```

The ` genomicranges.from_pandas(df_query)` appears to need to be ` genomicranges.GenomicRanges.from_pandas(df_query)`

And the `queryType` parameter to `find_overlaps` appears to have been removed.

Can you make the documentation vignettes run so they stay up-to-date?

**Comment by jkanche** [comment]
Apologies, I overlooked at the tutorial. This recent version should go live soon and will update the tutorial. Thank you for catching this!
