### ISSUE TITLE
Add missing dependency on joblib

### ISSUE THREAD

**Issue by mmokrejs** [BiocPy/GenomicRanges#75]
Following your example from `README.md` I get:

```
>>> subject = genomicranges.read_ucsc(genome="hg38")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/foo/genomicranges/lib/python3.11/site-packages/genomicranges/io/ucsc.py", line 61, in read_ucsc
    data = parse_gtf(path, compressed=compressed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/foo/genomicranges/lib/python3.11/site-packages/genomicranges/io/gtf.py", line 58, in parse_gtf
    from joblib import Parallel, delayed
ModuleNotFoundError: No module named 'joblib'
>>> 
```

**Comment by jkanche** [comment]
The package specified additional requirements that installs these optional packages.

```sh
pip install genomicranges[optional]
```

I'll add this to the documentation. Thank you for raising this issue.

**Comment by mmokrejs** [comment]
> The package specified additional requirements that installs these optional packages.
> 
> ```shell
> pip install genomicranges[optional]
> ```
> 

Maybe I missed that, I just did `pip install genomicranges` per my shell history. I thought it will install all deps but this `[optional]` is fine with me.
