### ISSUE TITLE
`read_gtf` function works slowly

### ISSUE THREAD

**Issue by abearab** [BiocPy/GenomicRanges#84]
I aimed to load a GTF file that I downloaded from [GENCODE ](https://www.gencodegenes.org/human/) and I noticed `genomicranges.read_gtf` works very slowly! Personally, I gave up and switched to `biobear` (developed by @tshauck). I thought you might like to use the magic of "Rust as its backend". I'm big fan of **BiocPy** but so far the R alternatives are still faster. Any thoughts?

**Comment by jkanche** [comment]
Thank you for raising this. I haven't spent time writing parsers, exactly to take advantage of existing IO libraries like biobear. 

A simple solution is to add a `from_polars` interface. @tshauck, I would love to collaborate and would be really nice to add a `to_genomicranges()` method in biobear. Would that be of interest  for you or should we minimize the deps and keep them separate?

**Comment by tshauck** [comment]
Thanks for raising this @abearab! ... @jkanche that would be of interest to me. I don't mind managing the additional optional dependency (technically polars is optional for biobear). I can have a look and follow up after I see what it'd take.

**Comment by abearab** [comment]
> Thanks for raising this @abearab! ... @jkanche that would be of interest to me. I don't mind managing the additional optional dependency (technically polars is optional for biobear). I can have a look and follow up after I see what it'd take.

Of course! I'm looking forward to these updates and thank you both for quick responses!

___
Here are some example codes I used recently, maybe that helps:
```python
# Path to the GTF file
GTF = '~/genomes/hg38/gencode.v46/gencode.v46.annotation.gtf'

session = bb.new_session()

gtf_df = session.read_gtf_file(GTF).to_polars()
```

```python
# Filter for transcripts and create tx2gene DataFrame
tx2gene = gtf_df.filter(
    pl.col('type') == 'transcript'
).with_columns([
    pl.col('attributes').map_elements(
        lambda x: extract_attribute(x, 'transcript_id'), return_dtype=pl.Utf8).alias('transcript_id'),
    pl.col('attributes').map_elements(
        lambda x: extract_attribute(x, 'gene_id'), return_dtype=pl.Utf8).alias('gene_id')
]).select(['transcript_id','gene_id']).to_pandas()
```

```python
# Filter for genes and create gene2name DataFrame
gene2name = gtf_df.filter(
    pl.col('type') == 'gene'
).with_columns([
    pl.col('attributes').map_elements(
        lambda x: extract_attribute(x, 'gene_id'), return_dtype=pl.Utf8).alias('gene_id'),
    pl.col('attributes').map_elements(
        lambda x: extract_attribute(x, 'gene_name'), return_dtype=pl.Utf8).alias('gene_name')
]).select(['gene_id','gene_name']).to_pandas()
```

**Comment by jkanche** [comment]
@abearab and @tshauck: 

Thank you for the issues and the connection with biobear. I added a [from_polars](https://biocpy.github.io/GenomicRanges/api/genomicranges.html#genomicranges.GenomicRanges.GenomicRanges.from_polars) class method to initialize `GenomicRanges` from a polars DataFrame. Example:

```python
from genomicranges import GenomicRanges
import polars as pl
from random import random

df = pl.DataFrame(
    {
        "seqnames": ["chr1", "chr2", "chr1", "chr3", "chr2"],
        "starts": [101, 102, 103, 104, 109],
        "ends": [112, 103, 128, 134, 111],
        "strand": ["*", "-", "*", "+", "-"],
        "score": range(0, 5),
        "GC": [random() for _ in range(5)],
    }
)

gr = GenomicRanges.from_polars(df)
print(gr)
```

There's a couple of different ways of initializing a GRanges (https://biocpy.github.io/GenomicRanges/tutorial.html#construct-a-genomicranges-object) object, Let me know if you run into any issues. In the mean time i will be looking into integrating with biobear's parsers.

**Comment by tshauck** [comment]
Very cool, not to be lazy, but I wonder if I need to add something to BioBear? It looks like I can do:

```python
from genomicranges import GenomicRanges
import biobear as bb

session = bb.new_session()

df = session.read_gtf_file("python/tests/data/test.gtf").to_polars()
df = df.rename({"seqname": "seqnames", "start": "starts", "end": "ends"})

gg = GenomicRanges.from_polars(dd)

# do stuff w/ a genomic ranges
print(len(gg), len(df))
77 77
```

which is somewhat annoying due to the renames, but seems to retain some flexibility for more general manipulation like filtering. If I'm not thinking of a good use case happy to add it, but I can at least at some an example to the docs of the integration.

**Comment by jkanche** [comment]
I agree, may be an example in the docs would help new users to jump between these representations.

**Comment by tshauck** [comment]
Update the docs here: https://www.wheretrue.dev/docs/exon/biobear/genomicranges-integration

**Comment by jkanche** [comment]
awesome! that looks great. 

likewise, I've also added the snippet to the README this morning - https://github.com/BiocPy/GenomicRanges?tab=readme-ov-file#from-biobear.

Hope this helps!
